meetups/4/blp1526.md

Add meetups/4/blp1526.md

---

meetups/4/ucan_lab.md

add ucan_lab.md

---

meetups/4/toyoshima.md

check-in toyoshima

---

meetups/7/treby.md

add treby for 7.

---

meetups/10/TaKesso.md

よろしくお願いいたします...！
（最後に今日の成果を追記するので[WIP]にしてます）

[WIP] check-in & out / TaKesso

---

meetups/10/seekworser.md

本日の成果を追記しました。
また、名前欄を修正いたしました。
よろしくお願いします。

modify meetups/10/seekworser.md (write today's result)

---

meetups/11/TaKesso.md

check-in#11_takesso

---

meetups/11/rednes.md

add meetups 11 rednes.md

---

meetups/11/TaKesso.md

check-out#11_takesso

---

meetups/12/rednes.md

check-out meetups 12 rednes.md

---

meetups/14/sasaki-ryu.md

成果を書くのが早いのは、諦めたからではありません……(遠い目)

update 14 sasakiryu.md

---

meetups/14/rednes.md

update meetups 14 rednes.md

---

PITCHME.md

成果発表について、PITCHME.mdに、以下の文章でついかしました。
```
2~3minでモニターを使って是非今日の成果を皆さんで共有し合いましょう:sparkles:
ref. [過去の発表](https://gitpitch.com/koki1023/2018-08-25_mokumoku)
```

add about results announcement

---

meetups/17/rednes.md

add meetups 17 rednes.md

---

meetups/17/rednes.md

update meetups 17 rednes.md

---

meetups/18/tanaken0515.md

Checkout: tanaken0515

---

connpass.md

修正内容
- LT　参考サイトの追加
- リンクがきれてしまっていたURLの修正
- Introductionの資料のURL追加

LT参考サイトとリンク切れのURLの修正

---

meetups/23/kpt.md

次回分（11月24日 # 23）のdirを作成しました。
ご確認お願いします😊

Add 23meetup folder

---

connpass.md

githubのfrokに関する記述のurlを追加しておきました。

add github fork url

---

meetups/24/nyamanaka.md

下記です、よろしくお願いします
PythonのWebフレームワークPyramidを触っていて、DBがまだなかったのでPostgreSQLに接続するあたり、migrationファイルの初期生成あたりやってました
- PostgreSQLへ接続する.iniファイルの設定 ◯
- migration ×
環境周りなのでpsycopg2-binaryがAlpine Linux上でインストールできなくてハマってました

nyamanaka add check-out

---

PITCHME.md
connpass.md

- connpass
- gitpitch
のmarkdownにて以下の記述を追加
- chromecastの接続方法
- slackのstatus設定について

add chromecast and slack status description

---

meetups/25/nyamanaka.md

add meetups/24/nyamanaka.md 2018-12-08

---

meetups/27/kpt.md

次回分（12月22日 # 27）のdirを作成しました。
ご確認お願いします◎

Add 27meetup folder

---

meetups/27/nyamanaka.md

add meetups/27/nyamanaka.md 2018-12-22

---

meetups/27/rednes.md

add rednes.md

---

meetups/27/nyamanaka.md

add check-out 2018-12-22

---

meetups/30/cidermitaina.md

Add meetups/30/cidermitaina.md

---

meetups/31/kpt.md

次回分（1月19日 # 31）のdirを作成しました。
ご確認お願いします◎

Add 31meetup folder

---

meetups/31/nyamanaka.md

add check-in 2019-01-19

---

meetups/31/nyamanaka.md

add check-out 2019-01-19

---

meetups/32/cidermitaina.md

Add meetups/32/cidermitaina.md

---

meetups/33/tanaken0515.md

Check-Out tanaken0515

---

meetups/38/cidermitaina.md

Add meetups/38/cidermitaina.md

---

meetups/38/96salix.md

実施内容追加@96salix

---

.circleci/config.yml
functions/package-lock.json
functions/package.json

Implement to deploy firebase functions by circleci.
when merge branch master, deploy function.
see also: 
- https://circleci.com/docs/2.0/deployment-integrations/#firebase
- https://circleci.com/setup-project/gh/shinjuku-mokumoku/shinjuku-mokumoku

Deploy function by circle ci

---

Dockerfile
README.md
docker-compose.yaml
functions/package-lock.json

dockerize local environment for development functions

dockerize local environment for development functions

---

meetups/40/nyamanaka.md

nyamanaka check-in 2019-03-23 今日やること

---

meetups/40/igrep.md

igrep check-in 2019-03-23

---

meetups/40/igrep.md

igrep checkout at 2019-03-23

---

meetups/40/nyamanaka.md

nyamanaka check-out 2019-03-23 今日やったこと

---

.circleci/config.yml
functions/Dockerfile
functions/deploy_functions.js
functions/package-lock.json
functions/package.json

avoid annoying function deploy error 🔪

only deploy functions when included functions diff

---

meetups/41/ohtsuka.md

ohtsukaの#41のやることを記述

---

meetups/42/cidermitaina.md

Add meetups/42/cidermitaina.md

---

meetups/42/kawasumi.md

スライド URL https://gitpitch.com/kawa1228/slides

fix: 今日の成果

---

meetups/43/cidermitaina.md

Add meetups/43/cidermitaina.md

---

meetups/44/cidermitaina.md

Add meetups/44/cidermitaina.md

---

.circleci/config.yml
scripts/connpass_event_creator.js

I'll fix
- install headless chrome dependencies on circleci
- fill automatically end date and time

Fix event creator

---

scripts/connpass_event_creator.js
scripts/event_publisher.js

Solve below problems
- cant install chronium on circleci user
- Datapicker overwraps submit button. so wait a few seconds
- Wait more second to upload banner image. Because network latency between circleci ci conatainer and connpass server

adjust to wait time for upload banner on connpass

---

meetups/48/shimohata.md

fix_shimohata.md

---

meetups/49/nyamanaka.md

nyamanaka check-in 2019-05-25 今日やること

---

meetups/49/nyamanaka.md

nyamanaka check-out 2019-05-25 今日やったこと

---

meetups/51/cidermitaina.md

Add meetups/51/cidermitaina.md

---

meetups/52/nzzy.md

はじめまして、nzzyです。6/15の#52分の紹介についてpull-requestしました。6/15はよろしくお願い致します。

add my entry for 52th

---

meetups/52/nzzy.md

commit complete report for 52th

---

README.md

I found broken links, so I fixed it.

Fix dead links in the README.md

---

meetups/55/sugiyama.md

add sugiyama.md

---

meetups/56/vikke.md

vikke / MATSUNAGA Ichiro checkin.

checkin vikke.

---

meetups/56/vikke.md

vikke checkout.

---

meetups/58/kikiki_kiki.md

check-in vol58

---

meetups/59/nzzy.md

Hi organaizer,
will you please merge my patch? 
Thanks,

add result for 59th meeting

---

meetups/59/murata.md

ローカルでsorbet language serverを起動して、vim上でsorbetに怒ってもらうところまでいけたので追記いたします。
もしよければマージお願いします 🙇

vim上でsorbetに怒ってもらうところまでいけたので追記

---

PITCHME.md

Organizerを辞めるので、gitpitchからcidermitainaを削除。
|BEFORE |AFTER  |
|---|---|
|![image](https://user-images.githubusercontent.com/23610884/62776230-e93e6100-bae4-11e9-9205-5a082a36fc72.png)|![image](https://user-images.githubusercontent.com/23610884/62776249-f5c2b980-bae4-11e9-885d-a6b0b5090b7d.png)|

Remove cidermitaina

---

meetups/64/nzzy.md

Hi, organaizer,
Will you merge my commit?
Thanks,
nzzy

add  my today's result to the 64th resume.

---

meetups/69/yutachaos.md

Yutachaos.md

---

meetups/71/yutagoto.md

checkout yutagoto 71

---

meetups/73/kaiba.md

update result to 73/kaiba

---

meetups/76/kikiki_kiki.md

:sparkles::cat2::dash: Add output @kikiki_kiki

---

meetups/79/y-wat.md

mod y-wat.md

---

meetups/81/TakumiKondo.md

Add TakumiKondo's profile for #81

---

meetups/81/y-wat.md

mod meetups/81/y-wat.md

---

meetups/81/TakumiKondo.md

概要
◎JdbcTeplateの学習
◎NamedParameterJdbcTemplateの学習

meetup #81 results

---

meetups/86/yutagoto.md

checkin 86 yutagoto :tada:

---

meetups/86/yutagoto.md

checkout 86 yutagoto :rocket:

---

meetups/87/yutagoto.md

:tada: checkin 87 yutagoto

---

meetups/87/taka.md

add result

---

meetups/87/yutagoto.md

:rocket: checkout 87 yutagoto

---

meetups/88/y-wat.md

add #88 y-wat

---

meetups/88/y-wat.md

mod meetups/88/y-wat.md

---

meetups/89/yutagoto.md

:door: checkin 89 yutagoto

---

meetups/89/y-wat.md

add 89 y-wat.md

---

meetups/89/yutagoto.md

:rocket: checkout 89 yutagoto

---

meetups/89/nakajima.md

update nakajima-introduce on 89

---

meetups/90/y-wat.md

add 90 y-wat.md

---

meetups/91/taiga.md

add vol.91

---

meetups/91/gangan.md

[Create] Create gangan.md

---

meetups/91/gangan.md

CSSナンモワカランで終わりました。
レビューお願いします。

[Update] update gangan.md

---

meetups/93/denik.md

mokumoku 93 denik.md add

---

meetups/93/y-wat.md

mod 93 y-wat.md

---

meetups/94/y-wat.md

add meetups/94/y-wat.md

---

meetups/106/y-wat.md

mod meetups/106/y-wat.md

---

meetups/107/y-wat.md

add meetups/107/y-wat.md
